### PR TITLE
fix: updated validations on address book

### PR DESCRIPTION
**Pull request by rashmi0301**
## Change Description

updated validations on address book 
updated province or state on all add forms

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: (Check only applicable)

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by FH-sandeepkaur1 — CHANGES_REQUESTED** [review]
Please take care of upper and lower case alphabets in placeholder and messages.

**Review by rashmi0301 — COMMENTED** [review]
updated uppercase placeholders and messages

**Comment by rashmi0301** [comment]
@FH-sandeepkaur1 plz check

**Review by rashmi0301 — COMMENTED** [review]
updated user address

**Review by FH-sandeepkaur1 — APPROVED** [review]

**Review by kunalfleethawks — APPROVED** [review]

**Pull request merged**
