### PR TITLE
fix: updated labels on aci and add validations on geofence

### PR DESCRIPTION
**Pull request by rashmi0301**
## Change Description

1. updated labels on aci form on detail page and add page 
2. updated the validations on geofence module over 2 fields 

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: (Check only applicable)

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by kunalfleethawks — CHANGES_REQUESTED** [review]
Please resolve the conflicts

**Review by kunalfleethawks — APPROVED** [review]

**Comment by kunalfleethawks** [comment]
@rashmi0301 there is error in the build
image

**Review by kunalfleethawks — CHANGES_REQUESTED** [review]
Fix the build errors

**Review by rashmi0301 — COMMENTED** [review]
removed extra div

**Comment by rashmi0301** [comment]
> Fix the build errors

@kunalfleethawks please review it . fixed all of the errors

**Review by kunalfleethawks — APPROVED** [review]

**Pull request merged**
