### PR TITLE
enhancement: placeholder in fields

### PR DESCRIPTION
**Pull request by Hardeep8587**
## Change Description

1. Placeholder for each field
2. Mark optional or not (for user experience)
3. custom class for placeholders in custom.css

Fixes # (issue)
1. not able to add, type mismatched, spelling error
## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist: (Check only applicable)

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Hardeep8587** [comment]
@amritfleethawks  @kunalfleethawks  please verify and merge, I added placeholders and tooltips to guide user.

**Review by kunalfleethawks — APPROVED** [review]
Looks good @Hardeep8587.

**Review by amritfleethawks — CHANGES_REQUESTED** [review]
Please resolve conflicts..

**Comment by Hardeep8587** [comment]
@amritfleethawks Done

**Comment by Hardeep8587** [comment]
@amritfleethawks  Done

**Review by amritfleethawks — APPROVED** [review]

**Pull request merged**
